version: '3.8'

services:
  glpi:
    image: diouxx/glpi:latest
    container_name: glpi
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      GLPI_INSTALL_AUTO: 1
      TZ: Europe/Paris
    volumes:
      - glpi_data:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb:10.5
    container_name: glpi_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: glpi
      MYSQL_USER: glpi
      MYSQL_PASSWORD: glpi
    volumes:
      - db_data:/var/lib/mysql

volumes:
  glpi_data:
  db_data:
